In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
single_mutants = pd.read_excel('/Users/claireleblanc/Downloads/41467_2019_12101_MOESM7_ESM.xlsx', sheet_name='1 AA change')
double_mutants = pd.read_excel('/Users/claireleblanc/Downloads/41467_2019_12101_MOESM7_ESM.xlsx', sheet_name='2 AA change')

In [41]:
WT_seqs = pd.read_excel('/Users/claireleblanc/Downloads/41467_2019_12101_MOESM7_ESM.xlsx', sheet_name='Synonymous')

In [43]:
WT_seqs['toxicity'].mean()

0.00487445332434398

In [31]:
single_mutants

,Pos,WT_AA,Mut,Nmut_nt,Nmut_aa,Nmut_codons,STOP,mean_count,is.reads0,sigma,toxicity,region,Pos_abs,mut_code
0,1,G,N,2,1,1,False,22.000000,True,0.037438,0.032210,290,290,G290N
1,1,G,T,2,1,1,False,17.333333,True,0.038981,-0.009898,290,290,G290T
2,1,G,R,2,1,1,False,3888.666667,True,0.005176,-0.010471,290,290,G290R
3,1,G,S,2,1,1,False,3635.666667,True,0.005341,0.030803,290,290,G290S
4,1,G,I,2,1,1,False,21.666667,True,0.035752,-0.054716,290,290,G290I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1261,1,S,Y,2,1,1,False,56.666667,True,0.029519,-0.119740,332,332,S332Y
1262,1,S,*,2,1,1,True,30.000000,True,0.033488,-0.240097,332,332,S332*
1263,1,S,C,1,1,1,False,3109.000000,True,0.007910,-0.142619,332,332,S332C
1264,1,S,W,2,1,1,False,29.666667,True,0.037607,-0.128531,332,332,S332W
1265,1,S,F,2,1,1,False,37.000000,True,0.032902,-0.128777,332,332,S332F

In [32]:
single_mutants = single_mutants.sort_values("Pos_abs")
single_mutants

,Pos,WT_AA,Mut,Nmut_nt,Nmut_aa,Nmut_codons,STOP,mean_count,is.reads0,sigma,toxicity,region,Pos_abs,mut_code
0,1,G,N,2,1,1,False,22.000000,True,0.037438,0.032210,290,290,G290N
629,1,G,F,2,1,1,False,15.666667,True,0.048122,0.120285,290,290,G290F
624,1,G,V,2,1,1,False,4481.000000,True,0.005138,0.012224,290,290,G290V
625,1,G,Y,2,1,1,False,20.333333,True,0.039583,0.057498,290,290,G290Y
626,1,G,*,2,1,1,True,24.333333,True,0.027824,-0.148892,290,290,G290*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,42,S,P,2,1,1,False,2313.000000,True,0.008440,-0.010472,332,373,S373P
896,42,S,T,2,1,1,False,3358.666667,True,0.007992,0.010441,332,373,S373T
895,42,S,K,3,1,1,False,16.000000,True,0.064971,0.065100,332,373,S373K
903,42,S,V,2,1,1,False,12.666667,True,0.057778,-0.023352,332,373,S373V
899,42,S,L,2,1,1,False,33.333333,True,0.039023,0.012388,332,373,S373L

In [33]:
single_mutants[single_mutants['Pos_abs'] == 332]

,Pos,WT_AA,Mut,Nmut_nt,Nmut_aa,Nmut_codons,STOP,mean_count,is.reads0,sigma,toxicity,region,Pos_abs,mut_code
1255,1,S,H,2,1,1,False,14.666667,True,0.058605,-0.053222,332,332,S332H
1256,1,S,P,2,1,1,False,18.666667,True,0.060915,0.227676,332,332,S332P
1257,1,S,L,2,1,1,False,39.000000,True,0.031589,-0.121192,332,332,S332L
1258,1,S,D,2,1,1,False,10.333333,True,0.073866,0.011296,332,332,S332D
1261,1,S,Y,2,1,1,False,56.666667,True,0.029519,-0.119740,332,332,S332Y
1260,1,S,V,2,1,1,False,33.000000,True,0.040529,-0.015831,332,332,S332V
1262,1,S,*,2,1,1,True,30.000000,True,0.033488,-0.240097,332,332,S332*
1263,1,S,C,1,1,1,False,3109.000000,True,0.007910,-0.142619,332,332,S332C
1254,1,S,M,2,1,1,False,36.666667,True,0.037205,0.036315,332,332,S332M
1259,1,S,G,2,1,1,False,3198.000000,True,0.008089,0.037623,332,332,S332G
1253,1,S,I,2,1,1,False,6950.000000,True,0.007269,-0.138627,332,332,S332I
632,1,S,T,2,1,1,False,2725.666667,True,0.008071,-0.116302,332,332,S332T
1265,1,S,F,2,1,1,False,37.000000,True,0.032902,-0.128777,332,332,S332F
630,1,S,K,2,1,1,False,47.333333,True,0.035742,0.140963,332,332,S332K
631,1,S,N,1,1,1,False,4311.000000,True,0.007779,0.058322,332,332,S332N
1264,1,S,W,2,1,1,False,29.666667,True,0.037607,-0.128531,332,332,S332W
633,1,S,R,1,1,1,False,10725.666667,True,0.007172,0.105820,332,332,S332R

In [34]:
curr_index = 290
WT_seq = "G"
curr_aa = "G"
for i in single_mutants.index:
    if curr_index == int(single_mutants.loc[i, "Pos_abs"]):
        if curr_aa == single_mutants.loc[i, "WT_AA"]:
            continue
        else:

            print("ERROR 1")
    elif curr_index + 1 == int(single_mutants.loc[i, "Pos_abs"]):
        WT_seq += single_mutants.loc[i, "WT_AA"]
        curr_index += 1
        curr_aa = single_mutants.loc[i, "WT_AA"]
        # print(curr_index, WT_seq)
    else:
        print(curr_index, int(single_mutants.loc[i, "Pos_abs"]))
        print("ERROR 2")

In [35]:
WT_seq

'GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWGMMGMLASQQNQSGPSGNNQNQGNMQREPNQAFGSGNNS'

In [47]:
(double_mutants["Pos1"] < double_mutants["Pos2"]).value_counts()

True    56730
Name: count, dtype: int64

In [70]:
single_mutants['aa_seq'] = [WT_seq[:int(single_mutants.loc[i, 'Pos']) - 1] + single_mutants.loc[i, 'Mut'] + WT_seq[int(single_mutants.loc[i, 'Pos']):] if not np.isnan(single_mutants.loc[i, 'Pos']) else WT_seq for i in single_mutants.index]
double_mutants['aa_seq'] = [WT_seq[:int(double_mutants.loc[i, 'Pos1']) - 1] + double_mutants.loc[i, 'Mut1'] + WT_seq[int(double_mutants.loc[i, 'Pos1']):int(double_mutants.loc[i, 'Pos2'])] + double_mutants.loc[i, 'Mut2'] + WT_seq[int(double_mutants.loc[i, 'Pos2']):] for i in double_mutants.index]

In [77]:
double_mutants['toxicity'] = double_mutants['toxicity_cond']

In [78]:
WT_avg_df = pd.DataFrame(WT_seqs.mean()).T
WT_avg_df['aa_seq'] = WT_seq

In [79]:
all_mutants = pd.concat([single_mutants, double_mutants, WT_avg_df])

In [ ]:
all_mutants[['aa_seq', 'toxicity']].rename(columns={'toxicity' : 'activity'}).to_csv()

                                                  aa_seq  activity
0      NNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG...  0.032210
1      TNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG... -0.009898
2      RNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG... -0.010471
3      SNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG...  0.030803
4      INSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG... -0.054716
...                                                  ...       ...
56726  GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAAYQASSW... -0.030744
56727  GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAAYQFSSW... -0.086802
56728  GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAAYQPSSW... -0.049587
56729  GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAAYQYSSW... -0.105390
0      GNSRGGGAGLGNNQGSNMGGGMNFGAFSINPAMMAAAQAALQSSWG...  0.004874

[57997 rows x 2 columns]